#define MAT_SHIPSIZE_X 116
#define MAT_SHIPSIZE_Y 54
#if 0
char *ship=
    "                                                                                                                    " "                                                                                                                    " "                                                                                                                    " "                                                                                                                    "
    "                                                                                                                    "
    "                                                         **                                                         "
    "                                                         **                                                         "
    "                                                         **                                                         "
    "                                                         **                                                         "
    "                                                         **                                                         "
    "                                                        ****                                                        "
    "                                                        ****                                                        "
    "                                                       ******                                                       "
    "                                                      ********                                                      "
    "                                                    ************                                                    "
    "                                                   **************                                                   "
    "                  XXX                             ****************                             XXX                  "
    "                XXXXXXX                           ****************                           XXXXXXX                "
    "                XXXXXXX                          ********..********                          XXXXXXX                "
    "                XXXXXXX                          *******....*******                          XXXXXXX                "
    "                XXXXXXX                         *******......*******                         XXXXXXX                "
    "                XXXXXXX                         *******......*******                         XXXXXXX                "
    "                XXXXXXX        1                ******........******                2        XXXXXXX                "
    "                XXXXXXX        1               *******........*******               2        XXXXXXX                "
    "                XXXXXXX        1               *******........*******               2        XXXXXXX                "
    "                XXXXXXX       111              *******........*******              222       XXXXXXX                "
    "                XXXXXXX       111             ********........********             222       XXXXXXX                "
    "                XXXXXXX*******************************........*******************************XXXXXXX                "
    "                XXXXXXX********************************......********************************XXXXXXX                "
    "                XXXXXXX*********************************....*********************************XXXXXXX                "
    "                XXXXXXX       111             ***********..***********             222       XXXXXXX                "
    "                XXXXXXX       111             ************************             222       XXXXXXX                "
    "                XXXXXXX       111             ************************             222       XXXXXXX                "
    "                XXXXXXX       111             ************************             222       XXXXXXX                "
    "                XXXXXXX       111             ************************             222       XXXXXXX                "
    "                XXXXXXX       111             ************************             222       XXXXXXX                "
    "                XXXXXXX       111             ************************             222       XXXXXXX                "
    "                XXXXXXX       111             ************************             222       XXXXXXX                "
    "                XXXXXXX       111             ************************             222       XXXXXXX                "
    "                XXXXXXX       111             ************************             222       XXXXXXX                "
    "                XXXXXXX       111             ************************             222       XXXXXXX                "
    "                XXXXXXX       111             ************************             222       XXXXXXX                "
    "                XXXXXXX       111             ************************             222       XXXXXXX                "
    "                XXXXXXX       111             ************************             222       XXXXXXX                "
    "                XXXXXXX**********************************************************************XXXXXXX                "
    "                XXXXXXX**********************************************************************XXXXXXX                "
    "                XXXXXXX**********************************************************************XXXXXXX                "
    "                XXXXXXX**********************************************************************XXXXXXX                "
    "                XXXXXXX       111             ************************             222       XXXXXXX                "
    "                XXXXXXX       111             ************************             222       XXXXXXX                "
    "                XXXXXXX        1                ********************                2        XXXXXXX                "
    "                  XXX                             ****************                             XXX                  "
    "                                                                                                                    "
    "                                                                                                                    "
    "                                                                                                                    ";
#endif

char *arg_ship_graphic =
    "                                                                                                                    "
    "                                                         XX                                                         "
    "                                                         XX                                                         "
    "                                                         XX                                                         "
    "                                                         XX                                                         "
    "                                                         XX                                                         "
    "                                                         XX                                                         "
    "                                                        XXXX                                                        "
    "                                                      XXXXXXXX                                                      "
    "                                                    *XXXXXXXXXX*                                                    "
    "                                                    *XXXXXXXXXX*                                                    "
    "                                                   **XXXXXXXXXX**                                                   "
    "                                                   **XXXXXXXXXX**                                                   "
    "                                                   **XXXX..XXXX**                                                   "
    "                                                  ***XXX....XXX***                                                  "
    "                                                 ****XX......XX****                                                 "
    "                                                *****XX......XX*****                                                "
    "                                               ******X........X******                                               "
    "                                              *******X........X*******                                              "
    "                               1             ********X........X********             2                               "
    "                               1            *********X........X*********            2                               "
    "                               1           **********X........X**********           2                               "
    "                              111         ***********X........X***********         222                              "
    "                              111        ************XX......XX************        222                              "
    "                              111       *************XXX....XXX*************       222                              "
    "                              111      **************XXXX..XXXX**************      222                              "
    "                              111     ***************XXXXXXXXXX***************     222                              "
    "                              111    ****************XXXXXXXXXX****************    222                              "
    "                              111   *****************XXXXXXXXXX*****************   222                              "
    "                              111  ******************XXXXXXXXXX******************  222                              "
    "                              111 *******************XXXXXXXXXX******************* 222                              "
    "                              111********************XXXXXXXXXX********************222                              "
    "                              11*********************XXXXXXXXXX*********************22                              "
    "                              1**********************XXXXXXXXXX**********************2                              "
    "                              ***********************XXXXXXXXXX***********************                              "
    "                             ************************XXXXXXXXXX************************                             "
    "                            *************************XXXXXXXXXX*************************                            "
    "                           **************************XXXXXXXXXX**************************                           "
    "                          ***************************XXXXXXXXXX***************************                          "
    "                          ***************************XXXXXXXXXX***************************                          "
    "                         ************              **XXXXXXXXXX**              ************                         "
    "                         ********                     XXXXXXXX                     ********                         "
    "                        *******11                      XXXXXX                      22*******                        "
    "                        ****  111                      XXXXXX                      222  ****                        "
    "                       **     111                      XXXXXX                      222     **                       "
    "                       *      111                      XXXXXX                      222      *                       "
    "                              111                      XXXXXX                      222                              "
    "                              111                       XXXX                       222                              "
    "                              111                       XXXX                       222                              "
    "                              111                      *XXXX*                      222                              "
    "                               1                     ***XXXX***                     2                               "
    "                                                ********XXXX********                                                "
    "                                                         XX                                                         "
    "                                                                                                                    "
    "                                                                                                                    ";

#define MAT_MISSILESIZE_X 63
#define MAT_MISSILESIZE_Y 36

char *mat_graph_missile[] =
{
  "                                                               "
  "                                                               "
  "                                                               "
  "                                                               "
  "                                                               "
  "                                                               "
  "                                                               "
  "                                                               "
  "                                                               "
  "                                                               "
  "                                                               "
  "                                                               "
  "                               X                               "
  "                               X                               "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                               X                               "
  "                                                               "
  "                                                               "
  "                                                               "
  "                                                               "
  "                                                               "
  "                                                               "
  "                                                               "
  "                                                               "
  "                                                               "
  "                                                               "
  "                                                               ",
  "                                                               "
  "                                                               "
  "                               X                               "
  "                               X                               "
  "                               X                               "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                              XXX                              "
  "                               X                               "
  "                                                               "
  "                                                               "
  "                                                               ",
  "                                                               "
  "                            XXXXXXX                            "
  "                           XXXXXXXXX                           "
  "                           XXXXXXXXX                           "
  "                          XXXXXXXXXXX                          "
  "                          XXXXXXXXXXX                          "
  "                          XXXXXXXXXXX                          "
  "                          XXXXXXXXXXX                          "
  "                          XXXXXXXXXXX                          "
  "                          XXXXXXXXXXX                          "
  "                          XXXXXXXXXXX                          "
  "                          XXXXXXXXXXX                          "
  "                          XXXXXXXXXXX                          "
  "                          XXXXXXXXXXX                          "
  "                          XXXXXXXXXXX                          "
  "                          XXXXXXXXXXX                          "
  "                          XXXXXXXXXXX                          "
  "                          XXXXXXXXXXX                          "
  "                          XXXXXXXXXXX                          "
  "                          XXXXXXXXXXX                          "
  "                          XXXXXXXXXXX                          "
  "                          XXXXXXXXXXX                          "
  "                          XXXXXXXXXXX                          "
  "                          XXXXXXXXXXX                          "
  "                          XXXXXXXXXXX                          "
  "                          XXXXXXXXXXX                          "
  "                          XXXXXXXXXXX                          "
  "                          XXXXXXXXXXX                          "
  "                          XXXXXXXXXXX                          "
  "                          XXXXXXXXXXX                          "
  "                          XXXXXXXXXXX                          "
  "                          XXXXXXXXXXX                          "
  "                          XXXXXXXXXXX                          "
  "                          XXXXXXXXXXX                          "
  "                         XXXXXXXXXXXXX                         "
  "                       XXXXXXXXXXXXXXXXX                       "
  "                    XXXXXXXXXXXXXXXXXXXXXXX                    " };

#define MAT_AST_SIZE_X  90
#define MAT_AST_SIZE_Y  89

char *mat_graph_ast[] =
{
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                       XXXXXXXXXXXXXXXXXXX                                "
  "                               XXXXXXXXXXXXXXXXXXXXXXXXXXXXX                              "
  "                          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                           "
  "                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                       "
  "                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                     "
  "                  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                    "
  "                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                   "
  "              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                  "
  "             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                  "
  "            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                 "
  "           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                 "
  "          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                 "
  "          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                "
  "         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                "
  "         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                "
  "         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                "
  "         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                "
  "         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                "
  "         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                "
  "         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                "
  "         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                "
  "         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                "
  "         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                "
  "         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                "
  "         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                "
  "          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX               "
  "          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX               "
  "          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX               "
  "          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX               "
  "          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX               "
  "          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX               "
  "           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX               "
  "           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX               "
  "           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX               "
  "           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX               "
  "           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX               "
  "           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX               "
  "          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX               "
  "          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX               "
  "          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX               "
  "          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX               "
  "          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                "
  "         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                "
  "         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                "
  "         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                "
  "         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                "
  "         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                "
  "         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                "
  "         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                 "
  "         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                 "
  "         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                 "
  "         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                 "
  "         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                 "
  "         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                  "
  "         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                  "
  "         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                  "
  "         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                   "
  "          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                   "
  "          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                    "
  "          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                     "
  "          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                      "
  "          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                       "
  "           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                         "
  "           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                          "
  "           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                            "
  "            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                             "
  "            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                               "
  "             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                "
  "              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                  "
  "                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                     "
  "                 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                         "
  "                   XXXXXXXXXXXXXXXXXXXXXXXXXXX                                            "
  "                      XXXXXXXXXXXXXXXXXXXXX                                               "
  "                         XXXXXXXXXXXXXXX                                                  "
  "                              XXXXXX                                                      "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          ",
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                      XXXXXXXXXXXXX                                       "
  "                                    XXXXXXXXXXXXXXXXX                                     "
  "                                 XXXXXXXXXXXXXXXXXXXXXX                                   "
  "                                XXXXXXXXXXXXXXXXXXXXXXXXXX                                "
  "                              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                              "
  "                             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                             "
  "                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                            "
  "                           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                           "
  "                           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                           "
  "                          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                          "
  "                          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                          "
  "                          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                          "
  "                         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                          "
  "                         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                          "
  "                         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                          "
  "                         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                          "
  "                          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                           "
  "                          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                            "
  "                          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                            "
  "                         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                           "
  "                          XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX                           "
  "                          XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX                           "
  "                          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                            "
  "                          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                             "
  "                          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                "
  "                           XXXXXXXXXXXXXXXXXXXXXXXXXXX                                    "
  "                          XXXXXXXXXXXXXXXXXXXXXXXXX                                       "
  "                          XXXXXXXXXXXXXXXXXXXXX                                           "
  "                          XXXXXXXXXXXXXXXXXX                                              "
  "                          XXXXXXXXXXXXXXXX                                                "
  "                          XXXXXXXXXXXXXXX                                                 "
  "                          XXXXXXXXXXXXXXX                                                 "
  "                           XXXXXXXXXXXXX                                                  "
  "                              XXXXXXX                                                     "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
  "                                                                                          "
};
